#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

# Update package lists
sudo apt-get update
# Install Nginx
sudo apt-get install -y nginx
# Create a simple HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx for /redirect_me
echo "Configuring Nginx for /redirect_me..."
cat <<EOL | sudo tee /etc/nginx/sites-available/redirect >/dev/null
server {
    listen 80;
    server_name _;

    location /redirect_me {
        rewrite ^ https://www.youtube.com permanent;
    }
}
EOL

# Enable the new site
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
# Create a custom 404 page
echo "Creating custom 404 page..."
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx for the custom 404 page
echo "Configuring Nginx for custom 404 page..."
cat <<EOL | sudo tee /etc/nginx/sites-available/custom404 >/dev/null
server {
    listen 80 default_server;
    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOL

# Enable the custom 404 site
sudo ln -s /etc/nginx/sites-available/custom404 /etc/nginx/sites-enabled/
# Test Nginx configuration
sudo nginx -t
# Reload Nginx to apply changes
sudo service nginx reload
# Restart Nginx
sudo service nginx restart