#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page and a 301 redirect

# Update package lists
sudo apt-get update
# Install Nginx
sudo apt-get install -y nginx
# Start Nginx service
sudo service nginx start

# Create a simple HTML file
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

# Configure Nginx for the 301 redirect
cat <<EOL | sudo tee -a /etc/nginx/sites-available/default >/dev/null

location /redirect_me {
    return 301 https://google.com;
}
EOL

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
# Configure Nginx for the custom 404 page
sudo sed -i 's/#error_page 404 \/404.html;/error_page 404 \/custom_404.html;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
