#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
