#!/usr/bin/env bash
# Give info about file (exists, empty, file and not a directory)

file="school"

if [ -e "$file" ]; then
	echo "$file file exists"

	if [ -s "$file" ]; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f "$file" ]; then
		echo "$file is a regular file"
	fi

else
	echo "$file file does not exist"
fi
